const stages=[
 {title:"سلامة الموقع ومبادئ الاستجابة",desc:"تأمين المكان، استخدام الوقاية الشخصية، وتحديد الأولويات.",lesson:"لا تدخل موقعًا غير آمن. أوقف المركبة في مكان يحميك، ارتدِ القفازات، افحص مخاطر المرور والكهرباء والحريق، ثم اطلب الدعم عبر غرفة العمليات عند الحاجة. هذا المحتوى للتدريب ولا يغني عن دورة معتمدة أو تعليمات قائد الحالة.",questions:[
  ["وصلت إلى حادث مروري ليلاً، وهناك رائحة وقود ومركبة غير مستقرة. ما القرار الأكثر أمانًا؟",["الاقتراب بحذر من جهة المركبة","إطفاء هاتفك والاقتراب فورًا","تأمين مسافة آمنة، تحذير الموجودين، وطلب الجهات المختصة قبل الدخول","إخراج المصاب وحدك بسرعة"],2],
  ["أثناء ارتداء القفازات تمزقت عند التعامل مع دم. ما الإجراء الصحيح؟",["إكمال المهمة ثم غسل اليدين","نزعها بطريقة آمنة، تنظيف اليدين، وارتداء زوج جديد","رش مطهر على القفاز ومتابعة العمل","تغطية التمزق بشريط لاصق"],1],
  ["وجدت مصابًا قرب سلك كهربائي ساقط ولا تعرف إن كان التيار مفصولًا. ماذا تفعل؟",["تسحب المصاب بأداة معدنية","تقترب للتأكد من السلك","تمنع الاقتراب وتطلب فصل التيار من الجهة المختصة","ترش الماء حول السلك"],2],
  ["في حادث متعدد الإصابات، مصاب يمشي ويتحدث، وآخر صامت ولا يتنفس طبيعيًا. من تعطي الأولوية؟",["المصاب الصامت الذي لا يتنفس طبيعيًا","المصاب الذي يطلب المساعدة بصوت أعلى","المصاب الأقرب إلى المركبة","تنتظر وصول الفريق دون تقييم"],0]
 ]},
 {title:"التقييم الأولي والإنعاش",desc:"فحص الاستجابة والتنفس، طلب المساعدة، والتصرف في توقف القلب.",lesson:"بعد التأكد من أمان المكان، عرّف نفسك وافحص الاستجابة. إذا كان المصاب غير مستجيب، اطلب من شخص الاتصال بـ997 وإحضار جهاز مزيل الرجفان الآلي AED، ثم افحص التنفس الطبيعي بسرعة. عند غياب التنفس الطبيعي ابدأ الإنعاش القلبي الرئوي واستخدم AED فور توفره وفق تدريبك وتعليمات الجهاز.",questions:[
  ["بعد التأكد من أمان المكان، مصاب بالغ لا يستجيب ويتنفس بلهاث متقطع. كيف تفسر الحالة؟",["تنفس طبيعي ويكفي مراقبته","علامة محتملة على توقف القلب تستدعي طلب AED وبدء CPR وفق التدريب","نوبة قلق فقط","إصابة بسيطة في الصدر"],1],
  ["أثناء CPR وصل AED وطلب تحليل النظم. ما التصرف الصحيح؟",["إيقاف الضغط وإبعاد الجميع عن المصاب أثناء التحليل واتباع التعليمات","استمرار الضغط أثناء التحليل","نزع اللصقات قبل التحليل","نقل المصاب إلى وضع الجلوس"],0],
  ["أثناء ضغطات الصدر تلاحظ أن الصدر لا يرتد بالكامل بعد كل ضغطة. ما التصحيح الأهم؟",["زيادة سرعة الضغط قدر الإمكان","السماح بارتداد الصدر الكامل وتقليل التوقفات","التوقف دقيقة بعد كل خمس ضغطات","الضغط على البطن بدل الصدر"],1],
  ["مصاب فاقد الوعي يتنفس طبيعيًا، لكن توجد آلية إصابة قوية للرقبة. ما الأولوية؟",["تحريكه فورًا إلى وضع الإفاقة","تثبيت الرأس والرقبة قدر الإمكان ومراقبة مجرى الهواء حتى وصول الفريق","إعطاؤه ماءً","تركه دون مراقبة"],1]
 ]},
 {title:"النزيف والصدمة والكسور",desc:"السيطرة على النزيف، مراقبة الصدمة، وتثبيت الإصابات.",lesson:"للنزيف الشديد استخدم الضغط المباشر المستمر بضماد، ولا ترفع الضماد المبلل بل أضف فوقه. في نزيف الأطراف المهدد للحياة استخدم العاصبة التجارية إذا كنت مدربًا عليها وسجّل وقت وضعها. لا تحاول إعادة العظم أو دفعه، وثبّت الطرف في وضعه وراقب المصاب حتى تسليمه.",questions:[
  ["نزيف نابض من فخذ مصاب لا يستجيب للضغط المباشر، وأنت مدرب على استخدام العاصبة. ما الإجراء الأنسب؟",["وضع عاصبة تجارية أعلى النزيف وتسجيل وقتها وطلب الإخلاء العاجل","إزالة الضماد كل دقيقة","وضع الثلج فوق الجرح فقط","إعطاء المصاب مشروبًا"],0],
  ["بعد وضع ضماد على نزيف، تشبّع بالدم لكنه ما زال ثابتًا في مكانه. ماذا تفعل؟",["إزالته لفحص الجرح","إضافة ضماد فوقه مع استمرار الضغط المباشر","غسل الجرح ونزع كل الضمادات","إيقاف الضغط لتهوية الجرح"],1],
  ["مصاب شاحب وبارد ومتعرق ومرتبك بعد نزيف، لكنه يتنفس. ما الأولوية؟",["إبقاؤه دافئًا، مراقبة مجرى الهواء والتنفس، وطلب الإخلاء العاجل","إجباره على المشي","إعطاؤه ماءً بكميات كبيرة","تركه ليستريح وحده"],0],
  ["كسر مفتوح مع نزيف، والعظم ظاهر. ما التصرف الذي يجب تجنبه؟",["تغطية الجرح بضماد مناسب","تثبيت الطرف في وضعه","إعادة العظم إلى داخل الجرح","مراقبة الدورة الدموية أسفل الإصابة"],2]
 ]},
 {title:"التواصل وتسليم الحالة",desc:"جمع المعلومات، التعامل المهني، وكتابة تقرير دقيق.",lesson:"استخدم أسلوبًا هادئًا ومحترمًا، واحصل على موافقة المصاب الواعي قبل الفحص متى أمكن. عند التسليم اذكر آلية الإصابة، حالة المصاب، العلامات المهمة، الإجراءات والوقت، وأي تغيرات طرأت. لا تشخّص أو تنشر صورًا وبيانات المصاب خارج القنوات الرسمية.",questions:[
  ["ما التسليم الأكثر فائدة للفريق الطبي؟",["وصف مختصر للشكوى وآلية الإصابة، العلامات، الإجراءات، أوقاتها، والاستجابة لها","ذكر الانطباع الشخصي فقط","ذكر اسم المصاب دون تفاصيل","تقديم رواية الشاهد دون التحقق من مصدرها"],0],
  ["مصاب واعٍ يرفض الفحص رغم إدراكه للمخاطر ولا يوجد خطر مباشر على الآخرين. ما الإجراء المهني؟",["إجباره على الفحص","شرح المخاطر والبدائل، احترام قراره، طلب الدعم وتوثيق الرفض","تصويره لإثبات الرفض","مغادرة الموقع دون إبلاغ الفريق"],1],
  ["شاهد متوتر يعطي معلومات متناقضة عن زمن الإصابة. كيف تحسن دقة المعلومات؟",["مقاطعته ورفع الصوت","طرح أسئلة مفتوحة ثم تثبيت الزمن التقريبي ومقارنته بمصادر أخرى","اعتماد أول إجابة فقط","نشر السؤال في مجموعة عامة"],1],
  ["طلب منك شخص غير مخول صورة تقرير المصاب بحجة التدريب. ماذا تفعل؟",["إرسال الصورة بعد إخفاء الاسم فقط","رفض المشاركة واتباع سياسة الخصوصية والقنوات الرسمية","نشرها في مجموعة خاصة","إرسالها إذا وافق الشاهد"],1]
 ]}
];
let state={name:"",age:"",discord:"",completed:[],scores:{},active:-1};
const $=s=>document.querySelector(s), show=id=>{["welcome","dashboard","training","quiz","final"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id));$("#homeBtn").classList.toggle("hidden",id==="welcome")};
function save(){localStorage.setItem("trainingState",JSON.stringify(state))}
function renderDashboard(){show("dashboard");$("#candidateLabel").textContent=state.name;$("#progressText").textContent=`${state.completed.length} / ${stages.length}`;$("#progressBar").style.width=`${state.completed.length/stages.length*100}%`;$("#stageList").innerHTML=stages.map((s,i)=>`<article class="stage ${state.completed.includes(i)?"done":""}"><span class="stage-status">${state.completed.includes(i)?"مكتملة":"غير مكتملة"}</span><p>المرحلة ${i+1}</p><h3>${s.title}</h3><p>${s.desc}</p>${state.scores[i]!==undefined?`<strong class="stage-score">النتيجة: ${state.scores[i]}٪</strong>`:""}<button class="primary" data-stage="${i}">${state.completed.includes(i)?"مراجعة":"بدء المرحلة"}</button></article>`).join("")}
function openStage(i){state.active=i;$("#stageEyebrow").textContent=`المرحلة ${i+1} من ${stages.length}`;$("#stageTitle").textContent=stages[i].title;$("#lesson").textContent=stages[i].lesson;show("training")}
function openQuiz(){const s=stages[state.active];$("#quizEyebrow").textContent=`اختبار المرحلة ${state.active+1}`;$("#quizTitle").textContent=s.title;$("#quizMessage").textContent="";$("#questions").innerHTML=s.questions.map((q,i)=>`<div class="question"><h3>${i+1}. ${q[0]}</h3>${q[1].map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}">${o}</label>`).join("")}</div>`).join("");show("quiz")}
async function submitQuiz(){const s=stages[state.active];let score=0;s.questions.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&Number(a.value)===q[2])score++});const pct=Math.round(score/s.questions.length*100);state.scores[state.active]=pct;if(pct<70){$("#quizMessage").textContent=`النتيجة ${pct}٪. لم تحقق الحد الأدنى 70٪، راجع المادة وأعد المحاولة.`;$("#quizMessage").style.color="var(--red)";save();return}if(!state.completed.includes(state.active))state.completed.push(state.active);save();if(state.completed.length===stages.length){const average=Math.round(Object.values(state.scores).reduce((sum,value)=>sum+value,0)/stages.length);let roleStatus="جاري منح رتبة الاجتياز...";try{const response=await fetch("/api/assign-role",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:state.discord})});if(response.ok)roleStatus="تم منح رتبة الاجتياز في Discord بنجاح.";else{const error=await response.json().catch(()=>({}));roleStatus=error.error||"تعذر منح الرتبة في Discord. تحقق من إعدادات البوت.";}}catch(error){roleStatus="تعذر الاتصال بخدمة Discord. تحقق من تشغيل الخادم."; }$("#finalSummary").innerHTML=`<div class="result-grid"><div><span>المتقدم</span><strong id="resultName"></strong></div><div><span>العمر</span><strong>${state.age} سنة</strong></div><div><span>معرّف Discord</span><strong>${state.discord}</strong></div><div><span>المتوسط العام</span><strong>${average}٪</strong></div></div><hr><strong>تفصيل النتائج</strong><ul class="score-list">${stages.map((stage,index)=>`<li><span>المرحلة ${index+1}: ${stage.title}</span><strong>${state.scores[index]}٪</strong></li>`).join("")}</ul><p class="qualified">الحالة: مؤهل لتجاوز التدريب</p><p class="role-status">${roleStatus}</p>`;$("#resultName").textContent=state.name;show("final")}else renderDashboard()}
$("#startBtn").onclick=()=>{const name=$("#candidateName").value.trim(),age=$("#candidateAge").value.trim(),discord=$("#candidateDiscord").value.trim();if(!name||!age||!discord)return $("#welcomeError").textContent="أكمل الاسم والعمر ومعرّف Discord أولًا.";if(!/^\d{17,20}$/.test(discord))return $("#welcomeError").textContent="معرّف Discord يجب أن يكون رقمًا من 17 إلى 20 خانة.";const numericAge=Number(age);if(!Number.isInteger(numericAge)||numericAge<16||numericAge>80)return $("#welcomeError").textContent="العمر يجب أن يكون بين 16 و80 سنة.";state={name,age,discord,completed:[],scores:{},active:-1};save();renderDashboard()};
$("#stageList").onclick=e=>{const b=e.target.closest("[data-stage]");if(b)openStage(Number(b.dataset.stage))};$("#quizBtn").onclick=openQuiz;$("#submitQuiz").onclick=submitQuiz;$("#backBtn").onclick=renderDashboard;$("#printBtn").onclick=()=>window.print();$("#homeBtn").onclick=()=>{$("#candidateName").value=state.name;$("#candidateAge").value=state.age;$("#candidateDiscord").value=state.discord;show("welcome")};
let saved=null;try{saved=JSON.parse(localStorage.getItem("trainingState")||"null")}catch(error){localStorage.removeItem("trainingState")}if(saved&&typeof saved.name==="string"&&saved.name){state={...state,...saved,scores:saved.scores||{}};renderDashboard()}else show("welcome");
