const stages=[
 {title:"سلامة الموقع ومبادئ الاستجابة",desc:"تأمين المكان، استخدام الوقاية الشخصية، وتحديد الأولويات.",lesson:"لا تدخل موقعًا غير آمن. أوقف المركبة في مكان يحميك، ارتدِ القفازات، افحص مخاطر المرور والكهرباء والحريق، ثم اطلب الدعم عبر غرفة العمليات عند الحاجة. هذا المحتوى للتدريب ولا يغني عن دورة معتمدة أو تعليمات قائد الحالة.",questions:[
  ["قبل الاقتراب من مصاب فاقد الوعي، ما أول خطوة؟",["التأكد من خلو المكان من أخطار تهددك وتهدد المصاب","إعطاء المصاب ماءً بسرعة","تحريك المصاب إلى أقرب مكان دون فحص"],0],
  ["ما الطريقة الصحيحة لتقليل انتقال العدوى أثناء الإسعاف؟",["ارتداء القفازات وغسل اليدين قبل وبعد تقديم المساعدة","ارتداء القفازات دون تغييرها بين المصابين","استخدام العطر بدل غسل اليدين"],0],
  ["وجدت سلكًا كهربائيًا ساقطًا قرب المصاب. ماذا تفعل؟",["تبتعد وتمنع الآخرين من الاقتراب وتطلب فصل التيار من المختصين","تسحب المصاب بيديك فورًا","تلمس السلك للتأكد من وجود الكهرباء"],0],
  ["أمام عدة مصابين، من تبدأ بتقييمه؟",["المصاب الذي لديه خطر مباشر على مجرى الهواء أو التنفس أو الدورة الدموية","المصاب الذي يصرخ بأعلى صوت","أول شخص تعرفه في الموقع"],0]
 ]},
 {title:"التقييم الأولي والإنعاش",desc:"فحص الاستجابة والتنفس، طلب المساعدة، والتصرف في توقف القلب.",lesson:"بعد التأكد من أمان المكان، عرّف نفسك وافحص الاستجابة. إذا كان المصاب غير مستجيب، اطلب من شخص الاتصال بـ997 وإحضار جهاز مزيل الرجفان الآلي AED، ثم افحص التنفس الطبيعي بسرعة. عند غياب التنفس الطبيعي ابدأ الإنعاش القلبي الرئوي واستخدم AED فور توفره وفق تدريبك وتعليمات الجهاز.",questions:[
  ["كيف تتحقق من استجابة المصاب البالغ؟",["نادِه بصوت واضح وربّت على كتفيه بلطف دون هز عنيف","صفعه على الوجه عدة مرات","صب الماء على وجهه"],0],
  ["مصاب لا يستجيب ولا يتنفس بشكل طبيعي. ما الإجراء الأول؟",["اطلب الاتصال بـ997 وإحضار AED وابدأ CPR وفق تدريبك","ضعه في وضع الجلوس وانتظر","أعطه طعامًا أو شرابًا"],0],
  ["ما العمق التقريبي لضغطات الصدر للبالغ أثناء CPR؟",["نحو 5 إلى 6 سم مع السماح بارتداد الصدر","نحو نصف سنتيمتر فقط","أكثر من 10 سم دائمًا"],0],
  ["ماذا تفعل إذا بدأ المصاب يتنفس طبيعيًا بعد CPR؟",["راقب تنفسه وضعه في وضع الإفاقة إذا لم توجد إصابة تمنع ذلك وانتظر الفريق","تتركه وحده وتغادر","تعطيه دواءً مباشرة"],0]
 ]},
 {title:"النزيف والصدمة والكسور",desc:"السيطرة على النزيف، مراقبة الصدمة، وتثبيت الإصابات.",lesson:"للنزيف الشديد استخدم الضغط المباشر المستمر بضماد، ولا ترفع الضماد المبلل بل أضف فوقه. في نزيف الأطراف المهدد للحياة استخدم العاصبة التجارية إذا كنت مدربًا عليها وسجّل وقت وضعها. لا تحاول إعادة العظم أو دفعه، وثبّت الطرف في وضعه وراقب المصاب حتى تسليمه.",questions:[
  ["ما أفضل طريقة للسيطرة على نزيف خارجي شديد في البداية؟",["الضغط المباشر القوي والمستمر بضماد مناسب","غسل الجرح بالماء فقط","رفع اليد عن الجرح كل دقيقة"],0],
  ["إذا كان جسم غريب مغروسًا في الجرح، ماذا تفعل؟",["لا تنزعه؛ اضغط حوله وثبّت الجسم واطلب المساعدة الطبية","تنزعه بسرعة ثم تغلق الجرح","تدفعه إلى داخل الجرح"],0],
  ["ما التصرف المناسب عند الاشتباه بصدمة لدى المصاب؟",["أبقِه دافئًا وراقب وعيه وتنفسه ولا تعطه طعامًا أو شرابًا","تجعله يمشي لتحسين الدورة الدموية","تعطيه منبهًا أو دواءً"],0],
  ["عند الاشتباه بالتواء في الكاحل، ما الإجراء الأول؟",["إراحة الطرف وتثبيته ورفعُه ووضع كمادة باردة ملفوفة عند الإمكان","تدليك الموضع بقوة","إجبار المصاب على المشي"],0]
 ]},
 {title:"التواصل وتسليم الحالة",desc:"جمع المعلومات، التعامل المهني، وكتابة تقرير دقيق.",lesson:"استخدم أسلوبًا هادئًا ومحترمًا، واحصل على موافقة المصاب الواعي قبل الفحص متى أمكن. عند التسليم اذكر آلية الإصابة، حالة المصاب، العلامات المهمة، الإجراءات والوقت، وأي تغيرات طرأت. لا تشخّص أو تنشر صورًا وبيانات المصاب خارج القنوات الرسمية.",questions:[
  ["ما الذي يجب ذكره عند تسليم المصاب للفريق الطبي؟",["الشكوى الرئيسية، العلامات الملحوظة، الإجراءات، ووقت حدوثها","رأي شخصي غير مؤكد عن التشخيص","المعلومات التي تبدو ممتعة فقط"],0],
  ["كيف تتعامل مع مصاب واعٍ قبل فحصه؟",["عرّف بنفسك واشرح ما ستفعله واطلب موافقته متى كان ذلك ممكنًا","تبدأ الفحص دون إخباره","تطلب من أحد تصويره"],0],
  ["ما السؤال المفيد لشاهد رأى بداية الحالة؟",["ماذا حدث ومتى بدأ وما الذي تغيّر منذ ذلك الوقت؟","هل تظن أن المصاب سيموت؟","لماذا لم تتصرف بدلًا منا؟"],0],
  ["كيف تحافظ على خصوصية المصاب؟",["تشارك بياناته فقط مع الفريق المختص وعبر القنوات الرسمية","تنشر صورته في وسائل التواصل","ترسل معلوماته إلى مجموعة عامة"],0]
 ]}
];
let state={name:"",age:"",discord:"",completed:[],scores:{},active:-1};
const $=s=>document.querySelector(s), show=id=>{["welcome","dashboard","training","quiz","final"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id));$("#homeBtn").classList.toggle("hidden",id==="welcome")};
function save(){localStorage.setItem("trainingState",JSON.stringify(state))}
function renderDashboard(){show("dashboard");$("#candidateLabel").textContent=state.name;$("#progressText").textContent=`${state.completed.length} / ${stages.length}`;$("#progressBar").style.width=`${state.completed.length/stages.length*100}%`;$("#stageList").innerHTML=stages.map((s,i)=>`<article class="stage ${state.completed.includes(i)?"done":""}"><span class="stage-status">${state.completed.includes(i)?"مكتملة":"غير مكتملة"}</span><p>المرحلة ${i+1}</p><h3>${s.title}</h3><p>${s.desc}</p>${state.scores[i]!==undefined?`<strong class="stage-score">النتيجة: ${state.scores[i]}٪</strong>`:""}<button class="primary" data-stage="${i}">${state.completed.includes(i)?"مراجعة":"بدء المرحلة"}</button></article>`).join("")}
function openStage(i){state.active=i;$("#stageEyebrow").textContent=`المرحلة ${i+1} من ${stages.length}`;$("#stageTitle").textContent=stages[i].title;$("#lesson").textContent=stages[i].lesson;show("training")}
function openQuiz(){const s=stages[state.active];$("#quizEyebrow").textContent=`اختبار المرحلة ${state.active+1}`;$("#quizTitle").textContent=s.title;$("#quizMessage").textContent="";$("#questions").innerHTML=s.questions.map((q,i)=>`<div class="question"><h3>${i+1}. ${q[0]}</h3>${q[1].map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}">${o}</label>`).join("")}</div>`).join("");show("quiz")}
async function submitQuiz(){const s=stages[state.active];let score=0;s.questions.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&Number(a.value)===q[2])score++});const pct=Math.round(score/s.questions.length*100);state.scores[state.active]=pct;if(pct<70){$("#quizMessage").textContent=`النتيجة ${pct}٪. لم تحقق الحد الأدنى 70٪، راجع المادة وأعد المحاولة.`;$("#quizMessage").style.color="var(--red)";save();return}if(!state.completed.includes(state.active))state.completed.push(state.active);save();if(state.completed.length===stages.length){const average=Math.round(Object.values(state.scores).reduce((sum,value)=>sum+value,0)/stages.length);let roleStatus="جاري منح رتبة الاجتياز...";try{const response=await fetch("/api/assign-role",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:state.discord})});if(response.ok)roleStatus="تم منح رتبة الاجتياز في Discord بنجاح.";else{const error=await response.json().catch(()=>({}));roleStatus=error.error||"تعذر منح الرتبة في Discord. تحقق من إعدادات البوت.";}}catch(error){roleStatus="تعذر الاتصال بخدمة Discord. تحقق من تشغيل الخادم."; }$("#finalSummary").innerHTML=`<div class="result-grid"><div><span>المتقدم</span><strong id="resultName"></strong></div><div><span>العمر</span><strong>${state.age} سنة</strong></div><div><span>معرّف Discord</span><strong>${state.discord}</strong></div><div><span>المتوسط العام</span><strong>${average}٪</strong></div></div><hr><strong>تفصيل النتائج</strong><ul class="score-list">${stages.map((stage,index)=>`<li><span>المرحلة ${index+1}: ${stage.title}</span><strong>${state.scores[index]}٪</strong></li>`).join("")}</ul><p class="qualified">الحالة: مؤهل لتجاوز التدريب</p><p class="role-status">${roleStatus}</p>`;$("#resultName").textContent=state.name;show("final")}else renderDashboard()}
$("#startBtn").onclick=()=>{const name=$("#candidateName").value.trim(),age=$("#candidateAge").value.trim(),discord=$("#candidateDiscord").value.trim();if(!name||!age||!discord)return $("#welcomeError").textContent="أكمل الاسم والعمر ومعرّف Discord أولًا.";if(!/^\d{17,20}$/.test(discord))return $("#welcomeError").textContent="معرّف Discord يجب أن يكون رقمًا من 17 إلى 20 خانة.";const numericAge=Number(age);if(!Number.isInteger(numericAge)||numericAge<16||numericAge>80)return $("#welcomeError").textContent="العمر يجب أن يكون بين 16 و80 سنة.";state={name,age,discord,completed:[],scores:{},active:-1};save();renderDashboard()};
$("#stageList").onclick=e=>{const b=e.target.closest("[data-stage]");if(b)openStage(Number(b.dataset.stage))};$("#quizBtn").onclick=openQuiz;$("#submitQuiz").onclick=submitQuiz;$("#backBtn").onclick=renderDashboard;$("#printBtn").onclick=()=>window.print();$("#homeBtn").onclick=()=>{$("#candidateName").value=state.name;$("#candidateAge").value=state.age;$("#candidateDiscord").value=state.discord;show("welcome")};
let saved=null;try{saved=JSON.parse(localStorage.getItem("trainingState")||"null")}catch(error){localStorage.removeItem("trainingState")}if(saved&&typeof saved.name==="string"&&saved.name){state={...state,...saved,scores:saved.scores||{}};renderDashboard()}else show("welcome");
