const stages=[
 {title:"الوصول الآمن وقيادة المشهد",desc:"ابدأ من سلامتك: أوقف المركبة، قيّم المخاطر، ونظّم الموقع قبل لمس المصاب.",lesson:"هذا هو التسلسل الأول في البلاغ: أوقف مركبة الاستجابة في مكان يحمي الفريق، ارتدِ معدات الوقاية، امسح الموقع بصريًا، حدّد مخاطر المرور والوقود والكهرباء، ثم اطلب الجهات المساندة. لا تتحول إلى مصاب ثانٍ من أجل الوصول بسرعة.",questions:[
  ["وصلت لبلاغ تصادم ليلاً، ورائحة وقود ومركبة مائلة تعيق الطريق. ما أول تصرف ميداني؟",["الاقتراب من الباب الأقرب للمصاب","إخراج المصاب فورًا دون تقييم","إيقاف مركبتك للحماية، عزل الخطر، تنبيه المرور وطلب الدعم قبل الدخول","تشغيل أضواء المركبة ثم دخول الموقع وحدك"],2],
  ["أثناء ارتداء القفازات تمزقت عند التعامل مع دم. ما الإجراء الصحيح؟",["إكمال المهمة ثم غسل اليدين","نزعها بطريقة آمنة، تنظيف اليدين، وارتداء زوج جديد","رش مطهر على القفاز ومتابعة العمل","تغطية التمزق بشريط لاصق"],1],
  ["وجدت مصابًا قرب سلك كهربائي ساقط ولا تعرف إن كان التيار مفصولًا. ماذا تفعل؟",["تسحب المصاب بأداة معدنية","تقترب للتأكد من السلك","تمنع الاقتراب وتطلب فصل التيار من الجهة المختصة","ترش الماء حول السلك"],2],
  ["في حادث متعدد الإصابات، مصاب يمشي ويتحدث، وآخر صامت ولا يتنفس طبيعيًا. من تعطي الأولوية؟",["المصاب الصامت الذي لا يتنفس طبيعيًا","المصاب الذي يطلب المساعدة بصوت أعلى","المصاب الأقرب إلى المركبة","تنتظر وصول الفريق دون تقييم"],0]
 ]},
 {title:"التقييم الأولي وإنقاذ الحياة",desc:"نفّذ فحصًا سريعًا ومنظمًا لمجرى الهواء والتنفس والدورة الدموية قبل التفاصيل.",lesson:"بعد تأمين المكان، عرّف نفسك وافحص الاستجابة. اطلب الاتصال بـ997 وإحضار AED، ثم قيّم التنفس الطبيعي بسرعة. تعامل مع اللهاث غير الطبيعي كعلامة خطرة، وابدأ الإنعاش وفق تدريبك وتعليمات الجهاز مع تقليل التوقفات.",questions:[
  ["بعد تأمين الموقع، وجدت مصابًا بالغًا لا يستجيب وله لهاث متقطع كل عدة ثوانٍ. ما القرار؟",["اعتباره يتنفس طبيعيًا ومراقبته فقط","اعتبار اللهاث غير طبيعي، طلب AED وبدء CPR وفق التدريب","إعطاؤه ماءً وانتظار تحسنه","وضعه جالسًا لتسهيل التنفس"],1],
  ["أثناء CPR وصل AED وطلب تحليل النظم. ما التصرف الصحيح؟",["إيقاف الضغط وإبعاد الجميع عن المصاب أثناء التحليل واتباع التعليمات","استمرار الضغط أثناء التحليل","نزع اللصقات قبل التحليل","نقل المصاب إلى وضع الجلوس"],0],
  ["أثناء ضغطات الصدر تلاحظ أن الصدر لا يرتد بالكامل بعد كل ضغطة. ما التصحيح الأهم؟",["زيادة سرعة الضغط قدر الإمكان","السماح بارتداد الصدر الكامل وتقليل التوقفات","التوقف دقيقة بعد كل خمس ضغطات","الضغط على البطن بدل الصدر"],1],
  ["مصاب فاقد الوعي يتنفس طبيعيًا، لكن توجد آلية إصابة قوية للرقبة. ما الأولوية؟",["تحريكه فورًا إلى وضع الإفاقة","تثبيت الرأس والرقبة قدر الإمكان ومراقبة مجرى الهواء حتى وصول الفريق","إعطاؤه ماءً","تركه دون مراقبة"],1]
 ]},
 {title:"النزيف والصدمة وتثبيت الإصابات",desc:"أوقف فقدان الدم، تعرّف على علامات الصدمة، وثبّت الإصابة دون زيادة الضرر.",lesson:"ابدأ بالنزيف المهدد للحياة: ضغط مباشر مستمر، ثم عاصبة تجارية عند الحاجة إذا كنت مدربًا عليها مع تسجيل الوقت. لا ترفع الضماد المشبع ولا تعِد العظم إلى مكانه. أبقِ المصاب دافئًا وراقب حالته حتى التسليم.",questions:[
  ["نزيف نابض من فخذ مصاب مستمر رغم الضغط المباشر، وأنت مدرب على العاصبة. ماذا تفعل؟",["وضع عاصبة تجارية أعلى النزيف، تسجيل وقتها وطلب الإخلاء العاجل","رفع العاصبة كل دقيقة لفحص الجلد","وضع الثلج وانتظار توقف النزيف","إعطاء المصاب شرابًا حتى يستعيد قوته"],0],
  ["بعد وضع ضماد على نزيف، تشبّع بالدم لكنه ما زال ثابتًا في مكانه. ماذا تفعل؟",["إزالته لفحص الجرح","إضافة ضماد فوقه مع استمرار الضغط المباشر","غسل الجرح ونزع كل الضمادات","إيقاف الضغط لتهوية الجرح"],1],
  ["مصاب شاحب وبارد ومتعرق ومرتبك بعد نزيف، لكنه يتنفس. ما الأولوية؟",["إبقاؤه دافئًا، مراقبة مجرى الهواء والتنفس، وطلب الإخلاء العاجل","إجباره على المشي","إعطاؤه ماءً بكميات كبيرة","تركه ليستريح وحده"],0],
  ["كسر مفتوح مع نزيف، والعظم ظاهر. ما التصرف الذي يجب تجنبه؟",["تغطية الجرح بضماد مناسب","تثبيت الطرف في وضعه","إعادة العظم إلى داخل الجرح","مراقبة الدورة الدموية أسفل الإصابة"],2]
 ]},
 {title:"التواصل والتوثيق وتسليم الحالة",desc:"اجمع المعلومات المهمة، احترم الخصوصية، وسلّم الحالة بلغة عملية قابلة للتنفيذ.",lesson:"استخدم أسلوبًا هادئًا واحصل على الموافقة متى أمكن. عند التسليم اذكر آلية الإصابة، الشكوى، العلامات المهمة، الإجراءات وأوقاتها، والاستجابة والتغيرات. افصل بين ما شاهدته وما نقله الشاهد، ولا تنشر صورًا أو بيانات خارج القنوات الرسمية.",questions:[
  ["عند وصول فريق الإسعاف، أي تسليم يساعده على اتخاذ القرار بسرعة؟",["ذكر آلية الإصابة والشكوى والعلامات والإجراءات وأوقاتها والاستجابة لها","ذكر توقعك لتشخيص المصاب فقط","ذكر اسم المصاب دون حالته","نقل كلام الشاهد دون توضيح أنه غير مؤكد"],0],
  ["مصاب واعٍ يرفض الفحص رغم إدراكه للمخاطر ولا يوجد خطر مباشر على الآخرين. ما الإجراء المهني؟",["إجباره على الفحص","شرح المخاطر والبدائل، احترام قراره، طلب الدعم وتوثيق الرفض","تصويره لإثبات الرفض","مغادرة الموقع دون إبلاغ الفريق"],1],
  ["شاهد متوتر يعطي معلومات متناقضة عن زمن الإصابة. كيف تحسن دقة المعلومات؟",["مقاطعته ورفع الصوت","طرح أسئلة مفتوحة ثم تثبيت الزمن التقريبي ومقارنته بمصادر أخرى","اعتماد أول إجابة فقط","نشر السؤال في مجموعة عامة"],1],
  ["طلب منك شخص غير مخول صورة تقرير المصاب بحجة التدريب. ماذا تفعل؟",["إرسال الصورة بعد إخفاء الاسم فقط","رفض المشاركة واتباع سياسة الخصوصية والقنوات الرسمية","نشرها في مجموعة خاصة","إرسالها إذا وافق الشاهد"],1]
 ]},
 {title:"الحروق والإصابات الحرارية",desc:"تقييم شدة الحرق، إيقاف مصدر الحرارة، وحماية الجلد المصاب.",lesson:"أوقف مصدر الحرارة بأمان، وبرّد الحرق بماء جارٍ فاتر لمدة مناسبة دون استخدام الثلج أو المواد المنزلية. انزع الحلي والملابس غير الملتصقة قبل التورم، ولا تنزع ما التصق بالجلد. غطِّ الحرق بضماد نظيف غير لاصق واطلب الإسعاف للحروق الواسعة أو العميقة أو التي تصيب الوجه واليدين والمفاصل.",questions:[
  ["انسكب سائل ساخن على ذراع مصاب، وما زالت الملابس الساخنة غير ملتصقة بالجلد. ما الإجراء الأول؟",["إزالة مصدر الحرارة والملابس غير الملتصقة ثم تبريد المنطقة بماء جارٍ فاتر","وضع الثلج مباشرة على الجلد","دهن الحرق بمعجون الأسنان","فتح الفقاعات الجلدية"],0],
  ["حرق عميق شاحب المظهر يحيط بالساعد مع تورم متزايد. ما القرار الأنسب؟",["تغطيته بضماد غير لاصق وطلب تقييم عاجل ومراقبة الدورة الدموية","وضع كريم تجميلي والانتظار","لف الطرف برباط ضاغط جدًا","إزالة الجلد المتضرر"],0],
  ["ما التصرف الصحيح مع فقاعة كبيرة ناتجة عن حرق؟",["عدم فتحها وتغطيتها بضماد نظيف غير لاصق","ثقبها بإبرة معقمة","فركها لإزالة الجلد","وضع الكحول عليها"],0],
  ["تعرض الوجه للدخان مع حرق حول الفم وبحة صوت. ما الأولوية؟",["اعتبارها إصابة محتملة لمجرى الهواء وطلب الإسعاف فورًا ومراقبة التنفس","إعطاؤه شرابًا باردًا","إبقاؤه مستلقيًا دون مراقبة","تغطية الوجه بغطاء محكم"],0]
 ]},
 {title:"الاختناق وانسداد مجرى الهواء",desc:"تمييز الانسداد الجزئي والكامل والتصرف الآمن حسب حالة المصاب.",lesson:"شجّع المصاب القادر على السعال على الاستمرار بالسعال وراقبه. إذا أصبح غير قادر على الكلام أو التنفس، اطلب المساعدة وطبّق مناورة إزالة الانسداد المناسبة وفق تدريبك وعمر المصاب. إذا فقد الوعي، ابدأ CPR واطلب AED، ولا تُدخل أصابعك عشوائيًا في فمه.",questions:[
  ["مصاب بالغ يسعل بقوة وقادر على الكلام بعد شرقة. ماذا تفعل؟",["تشجعه على السعال وتراقبه دون ضرب ظهره عشوائيًا","تقدم له الماء فورًا","تضع أصابعك في فمه","تجبره على الاستلقاء"],0],
  ["مصاب بالغ لا يستطيع الكلام أو التنفس ويمسك رقبته. ما الأولوية؟",["طلب المساعدة وتطبيق ضربات الظهر والدفع البطني وفق التدريب","إعطاؤه ماءً","تركه يسعل وحده دون مراقبة","وضعه على ظهره وانتظار تحسن حالته"],0],
  ["أثناء مساعدة مصاب مختنق فقد وعيه. ما الإجراء التالي؟",["إنزاله بأمان وبدء CPR وطلب AED وفحص الفم فقط عند رؤية جسم واضح","إدخال الأصابع عشوائيًا للبحث عن الجسم","تعليقه من قدميه","إعطاؤه شرابًا"],0],
  ["طفل واعٍ تعرض لاختناق شديد. ما الخطأ الذي يجب تجنبه؟",["استخدام نفس مناورة البالغين بقوة دون مراعاة عمره وحجمه","طلب الإسعاف مبكرًا","مراقبة الوعي والتنفس","اتباع بروتوكول التدريب المناسب للأطفال"],0]
 ]},
 {title:"التسمم والتعرض للمواد الخطرة",desc:"إيقاف التعرض، جمع المعلومات، وتجنب التدخلات التي تزيد الضرر.",lesson:"أبعد المصاب عن مصدر التسمم دون تعريض نفسك للخطر، واتصل بالطوارئ أو مركز السموم. احتفظ بعبوة المادة أو اسمها ووقت التعرض والكمية التقريبية. لا تُجبر المصاب على التقيؤ ولا تعطِ طعامًا أو شرابًا أو فحمًا نشطًا إلا بتوجيه مختص، وراقب مجرى الهواء والتنفس.",questions:[
  ["ابتلع مصاب مادة تنظيف ولا توجد عليه أعراض واضحة. ماذا تفعل؟",["الاتصال بمركز السموم أو الطوارئ وجمع اسم المادة والكمية والوقت دون تحفيز القيء","إجباره على التقيؤ","إعطاؤه الحليب تلقائيًا","انتظار ظهور الأعراض دون إبلاغ"],0],
  ["استنشاق مادة كيميائية داخل غرفة مغلقة أدى إلى دوار. ما الإجراء الآمن؟",["عدم الدخول دون حماية، تهوية المكان إن أمكن بأمان وإبعاد المصاب للهواء النقي وطلب المساعدة","الدخول سريعًا وحمل المصاب دون حماية","إشعال مروحة قرب التسرب مباشرة","إعطاء المصاب دواءً"],0],
  ["تلوث جلد المصاب بمادة كاوية. ما التصرف الأول؟",["إزالة الملابس الملوثة بحذر وغسل الجلد بماء جارٍ وفير وطلب توجيه مختص","فرك المادة بقوة","معادلة المادة بمادة كيميائية أخرى","تغطية الجلد دون غسله"],0],
  ["مصاب تسمم أصبح نعسانًا ويتقيأ. ما الأولوية؟",["مراقبة مجرى الهواء والتنفس ووضعه بأمان على جانبه عند الحاجة وطلب الإسعاف","إعطاؤه الطعام","إجباره على المشي","تركه ينام وحده"],0]
 ]},
 {title:"الطوارئ البيئية والإنهاك الحراري",desc:"التعامل مع الحرارة والبرد والبرق والجفاف مع حماية المسعف.",lesson:"انقل المصاب من البيئة الخطرة إلى مكان آمن، قيّم الوعي والتنفس، وبرّده تدريجيًا في حالات الإجهاد الحراري. ارتباك المصاب أو فقدانه الوعي مع حرارة مرتفعة علامة خطرة تستدعي الإسعاف والتبريد الفعال. في البرق، تأكد من زوال الخطر قبل لمس المصاب وابدأ التقييم الأساسي.",questions:[
  ["مصاب في جو شديد الحرارة مرتبك وجلده ساخن. ما التصرف الأنسب؟",["طلب الإسعاف فورًا ونقله لمكان بارد والبدء بالتبريد ومراقبة التنفس","إعطاؤه مشروبًا ساخنًا","تغطيته ببطانية سميكة","تركه ليستريح في الشمس"],0],
  ["مصاب واعٍ بإجهاد حراري وقادر على البلع. ما الإجراء المناسب؟",["نقله للظل وتخفيف الملابس وتبريده تدريجيًا وإعطاؤه رشفات مناسبة إذا لم توجد موانع","إجباره على شرب كمية كبيرة دفعة واحدة","إعطاؤه دواءً مجهولًا","إبقاؤه في السيارة المغلقة"],0],
  ["بعد صاعقة، أصبح المكان ما زال معرضًا لصواعق متكررة. ماذا تفعل؟",["الاحتماء أولًا وانتظار زوال الخطر قبل الاقتراب ثم تقييم المصاب","الركض للمصاب فورًا مهما كان الخطر","استخدام معدن للوصول إليه","رش الماء حوله"],0],
  ["مصاب بارد وواعٍ يرتجف لكنه يستطيع الكلام. ما التصرف الأفضل؟",["نقله لمكان دافئ وإزالة الملابس المبتلة وتدفئته تدريجيًا دون فرك الجلد","فرك الأطراف بقوة","وضعه أمام مصدر حرارة شديد مباشرة","إعطاؤه كحولًا"],0]
 ]}
];
let state={name:"",age:"",discord:"",completed:[],scores:{},cooldowns:{},active:-1};
const $=s=>document.querySelector(s), show=id=>{["welcome","dashboard","training","quiz","final"].forEach(x=>$("#"+x).classList.toggle("hidden",x!==id));$("#homeBtn").classList.toggle("hidden",id==="welcome")};
function save(){localStorage.setItem("trainingState",JSON.stringify(state))}
function cooldownRemaining(i){return Math.max(0,(state.cooldowns?.[i]||0)-Date.now())}
function formatCooldown(ms){const total=Math.ceil(ms/1000),minutes=Math.floor(total/60),seconds=String(total%60).padStart(2,"0");return `${minutes}:${seconds}`}
function renderDashboard(){show("dashboard");$("#candidateLabel").textContent=state.name;$("#progressText").textContent=`${state.completed.length} / ${stages.length}`;$("#progressBar").style.width=`${state.completed.length/stages.length*100}%`;$("#stageList").innerHTML=stages.map((s,i)=>{const remaining=cooldownRemaining(i),locked=remaining>0&&!state.completed.includes(i),label=locked?`متاح بعد ${formatCooldown(remaining)}`:(state.completed.includes(i)?"مراجعة":"بدء المرحلة");return `<article class="stage ${state.completed.includes(i)?"done":""} ${locked?"cooldown":""}"><span class="stage-status">${locked?"انتظار إجباري":(state.completed.includes(i)?"مكتملة":"غير مكتملة")}</span><p>المرحلة ${i+1}</p><h3>${s.title}</h3><p>${s.desc}</p>${state.scores[i]!==undefined?`<strong class="stage-score">النتيجة: ${state.scores[i]}٪</strong>`:""}${locked?`<p class="cooldown-note">أخطأت في المحاولة السابقة. راجع الدليل وانتظر 20 دقيقة قبل إعادة الاختبار.</p>`:""}<button class="primary" data-stage="${i}" ${locked?"disabled":""}>${label}</button></article>`}).join("");}
function openStage(i){if(cooldownRemaining(i)>0&&!state.completed.includes(i)){renderDashboard();return}state.active=i;$("#stageEyebrow").textContent=`المرحلة ${i+1} من ${stages.length}`;$("#stageTitle").textContent=stages[i].title;$("#lesson").textContent=stages[i].lesson;show("training")}
function openQuiz(){const s=stages[state.active];$("#quizEyebrow").textContent=`اختبار المرحلة ${state.active+1}`;$("#quizTitle").textContent=s.title;$("#quizMessage").textContent="بعد اختيار إجابة السؤال سيتم قفلها ولا يمكن تغييرها في هذه المحاولة.";$("#questions").innerHTML=s.questions.map((q,i)=>`<div class="question"><h3>${i+1}. ${q[0]}</h3>${q[1].map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}">${o}</label>`).join("")}</div>`).join("");show("quiz")}
async function submitQuiz(){const s=stages[state.active];let score=0;s.questions.forEach((q,i)=>{const a=document.querySelector(`input[name=q${i}]:checked`);if(a&&Number(a.value)===q[2])score++});const totalQuestions=s.questions.length,pct=Math.round(score/totalQuestions*100),wrong=totalQuestions-score;state.scores[state.active]=pct;if(pct<100){state.cooldowns[state.active]=Date.now()+20*60*1000;save();$("#quizMessage").textContent=`النتيجة: ${pct}٪ — الصحيح ${score} من ${totalQuestions}، والخاطئ ${wrong}. تم تسجيل النتيجة، وستتاح إعادة المرحلة بعد 20 دقيقة.`;$("#quizMessage").style.color="var(--red)";renderDashboard();return}if(!state.completed.includes(state.active))state.completed.push(state.active);delete state.cooldowns[state.active];save();if(state.completed.length===stages.length){const totalQuestions=stages.reduce((sum,stage)=>sum+stage.questions.length,0),totalCorrect=stages.reduce((sum,stage,index)=>sum+Math.round(stage.questions.length*state.scores[index]/100),0),totalWrong=totalQuestions-totalCorrect,overall=Math.round(totalCorrect/totalQuestions*100);let roleStatus="جاري منح رتبة الاجتياز...";try{const response=await fetch("/api/assign-role",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({userId:state.discord})});if(response.ok)roleStatus="تم منح رتبة الاجتياز في Discord بنجاح.";else{const error=await response.json().catch(()=>({}));roleStatus=error.error||"تعذر منح الرتبة في Discord. تحقق من إعدادات البوت.";}}catch(error){roleStatus="تعذر الاتصال بخدمة Discord. تحقق من تشغيل الخادم."; }$("#finalSummary").innerHTML=`<div class="result-grid"><div><span>المتقدم</span><strong id="resultName"></strong></div><div><span>العمر</span><strong>${state.age} سنة</strong></div><div><span>معرّف Discord</span><strong>${state.discord}</strong></div><div><span>الإجابات الصحيحة</span><strong>${totalCorrect} من ${totalQuestions}</strong></div><div><span>الإجابات الخاطئة</span><strong>${totalWrong}</strong></div><div><span>النتيجة العامة</span><strong>${overall}٪</strong></div></div><hr><strong>تفصيل النتائج</strong><ul class="score-list">${stages.map((stage,index)=>`<li><span>المرحلة ${index+1}: ${stage.title}</span><strong>${state.scores[index]}٪</strong></li>`).join("")}</ul><p class="qualified">الحالة: مؤهل لتجاوز التدريب</p><p class="role-status">${roleStatus}</p>`;$("#resultName").textContent=state.name;show("final")}else renderDashboard()}
$("#questions").addEventListener("change",e=>{if(!e.target.matches('input[type="radio"]'))return;const question=e.target.closest(".question");question.querySelectorAll('input[type="radio"]').forEach(input=>{input.disabled=true});question.querySelectorAll(".option").forEach(option=>option.classList.add("locked"));});
$("#startBtn").onclick=()=>{const name=$("#candidateName").value.trim(),age=$("#candidateAge").value.trim(),discord=$("#candidateDiscord").value.trim();if(!name||!age||!discord)return $("#welcomeError").textContent="أكمل الاسم والعمر ومعرّف Discord أولًا.";if(!/^\d{17,20}$/.test(discord))return $("#welcomeError").textContent="معرّف Discord يجب أن يكون رقمًا من 17 إلى 20 خانة.";const numericAge=Number(age);if(!Number.isInteger(numericAge)||numericAge<16||numericAge>80)return $("#welcomeError").textContent="العمر يجب أن يكون بين 16 و80 سنة.";state={name,age,discord,completed:[],scores:{},active:-1};save();renderDashboard()};
$("#stageList").onclick=e=>{const b=e.target.closest("[data-stage]");if(b&&!b.disabled)openStage(Number(b.dataset.stage))};$("#quizBtn").onclick=()=>{if(cooldownRemaining(state.active)>0&&!state.completed.includes(state.active)){renderDashboard();return}openQuiz()};$("#submitQuiz").onclick=submitQuiz;$("#exitQuizBtn").onclick=renderDashboard;$("#backBtn").onclick=renderDashboard;$("#printBtn").onclick=()=>window.print();$("#homeBtn").onclick=()=>{$("#candidateName").value=state.name;$("#candidateAge").value=state.age;$("#candidateDiscord").value=state.discord;show("welcome")};
let saved=null;try{saved=JSON.parse(localStorage.getItem("trainingState")||"null")}catch(error){localStorage.removeItem("trainingState")}if(saved&&typeof saved.name==="string"&&saved.name){state={...state,...saved,scores:saved.scores||{},cooldowns:saved.cooldowns||{}};renderDashboard()}else show("welcome");
setInterval(()=>{if($("#dashboard").classList.contains("hidden"))return;let expired=false;Object.keys(state.cooldowns).forEach(i=>{if(cooldownRemaining(i)===0){delete state.cooldowns[i];expired=true}});if(expired){save();renderDashboard();return}Object.keys(state.cooldowns).forEach(i=>{const button=$(`#stageList [data-stage="${i}"]`);if(button)button.textContent=`متاح بعد ${formatCooldown(cooldownRemaining(i))}`})},1000);
